import { useCallback } from "react";
import { useNavigate } from "react-router-dom";
import CRMContainer from "../components/CRMContainer";
import SubscriptionSection from "../components/SubscriptionSection";
import MainHeader from "../components/MainHeader";
import styles from "./CaseStudy1Impact.module.css";
const CaseStudy1Impact = () => {
  const navigate = useNavigate();

  const onPlatformTextClick = useCallback(() => {
    navigate("/our-platform");
  }, [navigate]);

  const onWhySattvaTextClick = useCallback(() => {
    navigate("/why-sattva");
  }, [navigate]);

  const onCaseStudiesText1Click = useCallback(() => {
    navigate("/case-study-example");
  }, [navigate]);

  const onAboutUsText1Click = useCallback(() => {
    navigate("/");
  }, [navigate]);

  const onTabContainer1Click = useCallback(() => {
    navigate("/case-study-1-solution");
  }, [navigate]);

  const onTabContainer2Click = useCallback(() => {
    navigate("/case-study-1-challenge");
  }, [navigate]);

  const onProjectContainerClick = useCallback(() => {
    navigate("/case-study-3-challenge");
  }, [navigate]);

  const onProjectContainer1Click = useCallback(() => {
    navigate("/case-study-2-challenge");
  }, [navigate]);

  const onLogoTrans1Click = useCallback(() => {
    navigate("/sattva-home-page");
  }, [navigate]);

  return (
    <div className={styles.caseStudy1Impact}>
      <div className={styles.postBodyParent}>
        <CRMContainer
          crmDescription="A prestigious institution that embodies diverse collections, groundbreaking research, and immersive experiences to reveal human history, science, art, and culture."
          crmTestingSolutionDescrip="Enabling Automated Accessibility Testing for a Globally Recognized Institution"
        />
        <div className={styles.howToSectionParent}>
          <div className={styles.howToSection}>
            <div className={styles.howToSection}>
              <div className={styles.implementingTheSattva}>
                Implementing the Sattva platform would have a transformative
                impact on the institution’s website. The automation of
                accessibility testing enables a more efficient and comprehensive
                evaluation of the site. By running multiple accessibility
                plugins simultaneously on the entirety of the website, Sattva
                can quickly pinpoint and highlight accessibility barriers. The
                consolidated report generated by the Sattva platform is an
                invaluable resource, providing recommendations for change and
                allowing this institution to prioritize accessibility issues in
                order to create more inclusive, seamless user experience for all
                visitors.
              </div>
              <div className={styles.line} />
              <div className={styles.line1} />
              <div className={styles.tab}>
                <div className={styles.theImpact}>The Impact</div>
              </div>
              <div className={styles.tab1} onClick={onTabContainer1Click}>
                <div className={styles.theSolution}>The Solution</div>
              </div>
              <div className={styles.tab2} onClick={onTabContainer2Click}>
                <div className={styles.theSolution}>The Challenge</div>
              </div>
            </div>
          </div>
          <div className={styles.itemParent}>
            <div className={styles.item}>
              <div
                className={styles.increaseInThe}
              >{`increase in the number of URLS tested simultaneously due to site-wide crawling `}</div>
              <div className={styles.x}>100x</div>
            </div>
            <div className={styles.divider} />
            <div className={styles.item1}>
              <div className={styles.reductionInTime}>
                reduction in time spent to configure the automated tests to less
                than 1 minute
              </div>
              <div className={styles.min}>{`< 1 min`}</div>
            </div>
            <div className={styles.divider1} />
            <div className={styles.item2}>
              <div
                className={styles.reductionInTime1}
              >{`reduction in time spent to run accessibility tests on multiple URLs `}</div>
              <div className={styles.div}>86%</div>
            </div>
          </div>
        </div>
      </div>
      <div className={styles.projectRowParent}>
        <div className={styles.projectRow}>
          <div className={styles.project} onClick={onProjectContainerClick}>
            <img
              className={styles.maskGroupIcon}
              alt=""
              src="/mask-group@2x.png"
            />
            <div className={styles.tint} />
            <div className={styles.content}>
              <div className={styles.secondaryButton}>
                <div className={styles.secondaryButtonText}>Learn More</div>
              </div>
              <div
                className={styles.highlightingAccessibilityImp}
              >{`Highlighting accessibility improvements within the DOE website using Sattva’s third party integration with aXe for WCAG and Section 508 compliance. `}</div>
              <b className={styles.creatingChangeWith}>
                Creating Change with Automated Accessibility Testing for the
                Department of Education
              </b>
            </div>
          </div>
          <div className={styles.project1} onClick={onProjectContainer1Click}>
            <img
              className={styles.maskGroupIcon1}
              alt=""
              src="/mask-group5@2x.png"
            />
            <div className={styles.tint} />
            <div className={styles.content1}>
              <div className={styles.secondaryButton1}>
                <div className={styles.secondaryButtonText}>Learn More</div>
              </div>
              <div
                className={styles.utilizingTheSattva}
              >{`Utilizing the Sattva platform to execute performance, accessibility, security, and functional testing in one go. `}</div>
              <b className={styles.creatingChangeWith}>
                Building a Comprehensive Testing Solution for a CRM Software
                Company
              </b>
            </div>
          </div>
        </div>
        <SubscriptionSection />
      </div>
      <MainHeader
        dimensions="/bxsearch3.svg"
        propTop="19.54%"
        propHeight="60.92%"
        propBottom="19.54%"
        propTop1="0%"
        propHeight1="100%"
        propBottom1="0%"
        onPlatformTextClick={onPlatformTextClick}
        onWhySattvaTextClick={onWhySattvaTextClick}
        onCaseStudiesText1Click={onCaseStudiesText1Click}
        onAboutUsText1Click={onAboutUsText1Click}
      />
      <img
        className={styles.logoTrans1}
        alt=""
        src="/logo--trans-1@2x.png"
        onClick={onLogoTrans1Click}
      />
    </div>
  );
};

export default CaseStudy1Impact;
